export const data = [
    { id: 1, name: 'Qatar', img: require('../../assets/Images/Flags/qatar.png') },
    { id: 2, name: 'Bahrain', img: require('../../assets/Images/Flags/behrain.png') },
    { id: 3, name: 'Pakistan', img: require('../../assets/Images/Flags/pakistan.png') },
    { id: 4, name: 'Egypt', img: require('../../assets/Images/Flags/egypt.png') },
    { id: 5, name: 'Alexandria' },
    { id: 6, name: 'Cairo' },
    { id: 7, name: 'Delta' },
    { id: 8, name: 'Upper Egypt',  },
    { id: 9, name: 'Algeria', img: require('../../assets/Images/Flags/algeria.png') },
    { id: 10, name: 'Iraq', img: require('../../assets/Images/Flags/iraq.png') },
    { id: 11, name: 'Baghdad' },
    { id: 12, name: 'Basra Governorate'},
    { id: 13, name: 'Kuwait', img: require('../../assets/Images/Flags/kuwait.png') },
    { id: 14, name: 'Al Jahra Governorate' },
    { id: 15, name: 'Kuwait City' },
    { id: 16, name: 'Tenth Region' },
    { id: 17, name: 'Lebanon', img: require('../../assets/Images/Flags/Lebonan.png') },
    { id: 18, name: 'Morroco', img: require('../../assets/Images/Flags/Morroco.png') },
    { id: 19, name: 'Oman', img: require('../../assets/Images/Flags/oman.png') },
    { id: 20, name: 'Jordan', img: require('../../assets/Images/Flags/jordan.png') },
    { id: 21, name: 'Amman' },
    { id: 22, name: 'Aqaba' },
    { id: 23, name: 'Irbid' },
    { id: 24, name: 'Zarqaa' },
    { id: 25, name: 'Saudia', img: require('../../assets/Images/Flags/Saudia.png') },
    { id: 26, name: 'Al Ahsa' },
    { id: 27, name: 'Al Qasim' },
    { id: 28, name: 'Aseer Province' },
    { id: 29, name: 'Dammam' },
    { id: 30, name: 'Hail Province' },
    { id: 31, name: 'Jeddah' },
    { id: 32, name: 'Medina' },
    { id: 33, name: 'Riyadh' },
    { id: 34, name: 'Tabuk' },
    { id: 35, name: 'Yemen', img: require('../../assets/Images/Flags/Yemen.png') },
    { id: 36, name: 'UAE', img: require('../../assets/Images/Flags/UAE.png') },
    { id: 37, name: 'Abu Dhabi' },
    { id: 38, name: 'Ajman Emirates' },
    { id: 39, name: 'Al Ain' },
    { id: 40, name: 'Dubai Emirate' },
    { id: 41, name: 'Fujairah' },
    { id: 42, name: 'Ras Al-Khaima' },
    { id: 43, name: 'Sharjah Emirate' },
    { id: 44, name: 'Umm Al Quwain' },
    { id: 45, name: 'Tunisia', img: require('../../assets/Images/Flags/Tunisia.png') },
];